FROM arm32v7/debian:stretch-slim
LABEL maintainer "Simon Jang <simonjisu@gmail.com>"

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
		build-essential \
		cmake \
		git \
		curl \
		vim \
		ca-certificates \
		apt-utils \
		man \
		tmux \
		less \
		wget \
		iputils-ping \
		software-properties-common \
		tzdata \
		locales \
		openssh-server \
		xauth \
		gpg-agent \
		gnupg2 \
		unzip \
		rsync \
		tk-dev \
		libncurses5-dev \
		libncursesw5-dev \
		libreadline6-dev \
		libdb5.3-dev \
		libgdbm-dev \
		libsqlite3-dev \
		libssl-dev \
		libbz2-dev \ 
		libexpat1-dev \
		liblzma-dev \
		zlib1g-dev &&\
    rm -rf /var/lib/apt/lists/*

RUN echo "ko_KR.UTF-8 UTF-8" >> /etc/locale.gen && locale-gen ko_KR.UTF-8
ENV LANG="ko_KR.UTF-8" LANGUAGE="ko_KR:en" LC_ALL="ko_KR.UTF-8"
RUN wget https://gist.githubusercontent.com/simonjisu/965bf3a284259104313a8f19f0c5ad55/raw/f82635ae999400f161028a2033fa5ec5a8f62687/install_python3.sh
RUN chmod +x ~/install_python3.sh && ~/install_python3.sh
ENV PYTHONPATH="/usr/local/bin:$PATH"
RUN update-alternatives --install /usr/local/bin/python python /usr/local/bin/python3.6 1
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py
RUN apt-get update && apt-get install -y --no-install-recommends \
		libffi-dev \
		libsasl2-dev \
		libldap2-dev

RUN pip install tqdm selenium bs4 superset pandas==0.23.4 sqlalchemy==1.2.18
RUN rm -rf ~/.cache/pip

# install chrome
RUN apt-get install -y --no-install-recommends \
		xvfb \
		libasound2 \
		libatk-bridge2.0-0 \
		libatk1.0-0 \
		libatspi2.0-0 \
		libcairo2 \
		libcups2 \
		libgdk-pixbuf2.0-0 \
		libgtk-3-0 \
		libnspr4 \
		libnss3 \
		libpango-1.0-0 \
		libpangocairo-1.0-0 \
		libxcomposite1 \
		libxcursor1 \
		libxi6 \
		libxrandr2 \
		libxtst6 \
		xdg-utils && \
		rm -rf /var/lib/apt/lists/*

RUN pip install xvfbwrapper

RUN wget -O ch-browser74-ubuntu1604-armhf.deb http://ports.ubuntu.com/pool/universe/c/chromium-browser/chromium-browser_74.0.3729.169-0ubuntu0.16.04.1_armhf.deb
RUN wget -O ch-driver74-ubuntu1604-armhf.deb http://ports.ubuntu.com/pool/universe/c/chromium-browser/chromium-chromedriver_74.0.3729.169-0ubuntu0.16.04.1_armhf.deb
RUN wget -O ch-codecs74-ubuntu1604-armhf.deb http://ports.ubuntu.com/pool/universe/c/chromium-browser/chromium-codecs-ffmpeg_74.0.3729.169-0ubuntu0.16.04.1_armhf.deb
RUN wget -O ch-codecsextra74-ubuntu1604-armhf.deb http://ports.ubuntu.com/pool/universe/c/chromium-browser/chromium-codecs-ffmpeg-extra_74.0.3729.169-0ubuntu0.16.04.1_armhf.deb
RUN dpkg -i ch-codecs74-ubuntu1604-armhf.deb
RUN dpkg -i ch-codecsextra74-ubuntu1604-armhf.deb
RUN dpkg -i ch-browser74-ubuntu1604-armhf.deb
RUN dpkg -i ch-driver74-ubuntu1604-armhf.deb
ENV PYTHONUNBUFFERED=1
WORKDIR /root